### ISSUE TITLE
Add "Start Time" and "End Time" Configuration Properties 

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/simple-trigger-component#1]
In order to [comply with component standards](https://github.com/openintegrationhub/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#get-new-and-updated-objects-polling), this component should have the following configuration options in the trigger:
* Start Time (string, optional): Indicates the begining time to start polling from (defaults to the begining of time)
* End Time (string, optional): If provided, don’t fetch records modified after this time (defaults to never)

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/simple-trigger-component/releases/tag/1.2.0
